# Generated by Django 6.1.1 on 2026-09-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="edge",
            table="edges",
        ),
        migrations.AlterModelTable(
            name="node",
            table="nodes",
        ),
        migrations.AlterModelTable(
            name="routequery",
            table="route_queries",
        ),
    ]
